version: "3.9"

services:
  web:
    container_name: ajh-website
    image: ajh-website_web
    build: .

    command: python /app/src/server.py

    ports:
      - "8080:8080"

    volumes:
      - /home/rpi2b/AJH-website/.env:/app/.env
      - /home/rpi2b/AJH-website/instance:/app/instance
      - /home/rpi2b/AJH-website/src:/app/src
      - /home/rpi2b/AJH-website/migrations:/app/migrations

    restart: unless-stopped